title: David Cardenas
show_downloads: true
theme: jekyll-theme-minimal
logo: /phtResumeCircled.png
description: LinkedIn: https://www.linkedin.com/in/davhercar/\nEmail: davidhdzcard@gmail.com\n Monterrey, Mexico.
